/*********************************************************************************************************************
 * Copyright (c) 2019, Infineon Technologies AG
 *
 * 
 * Distributed under the Boost Software License, Version 1.0.
 * 
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * 
 *********************************************************************************************************************/

#ifndef SBC_TLE94X1_H
#define SBC_TLE94X1_H

/* XML Version 0.0.6 */
#define SBC_XML_VERSION (00006)

#define CTRL_BUS_CTRL_0 (0x3) /*decimal 3*/

#define CTRL_BUS_CTRL_3 (0x0) /*decimal 0*/

#define CTRL_GPIO_CTRL (0x0) /*decimal 0*/

#define CTRL_HW_CTRL_0 (0x0) /*decimal 4*/

#define CTRL_HW_CTRL_1 (0x0) /*decimal 0*/

#define CTRL_HW_CTRL_2 (0x40) /*decimal 64*/

#define CTRL_HW_CTRL_3 (0x1) /*decimal 1*/

#define CTRL_M_S_CTRL (0x8) /*decimal 8*/

#define CTRL_PWM_CTRL (0x0) /*decimal 0*/

#define CTRL_PWM_FREQ_CTRL (0x0) /*decimal 0*/

#define CTRL_SWK_BTL0_CTRL (0x50) /*decimal 80*/

#define CTRL_SWK_CAN_FD_CTRL (0x0) /*decimal 0*/

#define CTRL_SWK_CDR_CTRL2 (0x1) /*decimal 1*/

#define CTRL_SWK_CDR_LIMIT_HIGH_CTRL (0x54) /*decimal 84*/

#define CTRL_SWK_CDR_LIMIT_LOW_CTRL (0x4C) /*decimal 76*/

#define CTRL_SWK_DATA_H_CTRL 0x00000000

#define CTRL_SWK_DATA_L_CTRL 0x00000000

#define CTRL_SWK_DLC_CTRL (0x0) /*decimal 0*/

#define CTRL_SWK_ID0_CTRL (0x0) /*decimal 0*/

#define CTRL_SWK_IDx_CTRL 0x00000000

#define CTRL_SWK_MASK_IDx_CTRL 0x00000000

#define CTRL_TIMER_CTRL (0x0) /*decimal 0*/

#define CTRL_WD_CTRL (0x15) /*decimal 21*/

#define CTRL_WK_CTRL_0 (0x0) /*decimal 0*/

#define CTRL_WK_CTRL_1 (0x01) /*decimal 1*/

#define CTRL_WK_PUPD_CTRL (0x0) /*decimal 0*/

#define LED_Math_extendedID (0x1) /*decimal 1*/

#define LED_Math_extendedIDMsk (0x1) /*decimal 1*/

#define MATH_Baudrate (0x2) /*decimal 2*/

#define MATH_CDR_FrequencyMHz (0x28) /*decimal 40*/

#define MATH_DoubleCDRFreq (0x0) /*decimal 0*/

#define MATH_EN_PN (0x0) /*decimal 0*/

#define MATH_PWM_DC (0.0)

#endif /* SBC_TLE94X1_H */
